var lth_solr_messages = {
    abstract: "Abstract",
    additionalLink: "Andra länkar",
    authorLastName: "Efternamn",
    authors: "Författare",
    close: "Stäng",
    courses: "Kurser",
    documents: "Dokument",
    doi: "DOI",
    edition: "Utgåva",
    electronicIsbns: "Elektroniska ISBN",
    event: "Event",
    export: "EXPORTERA SÖKRESULTATET",
    externalOrganisations: "Externa organisationer",
    filterSearchResult: "FILTRERA SÖKRESULTATET",
    fulltext: "Fulltext",
    hits: "träffar",
    hostPublicationTitle: "Titel på värdpublikation",
    in: "i",
    applyButtonText: 'Logga in och sök jobet',
    job: "jobb",
    jobAnstForm: "Anställningsform",
    jobTilltrade: "Tillträde",
    jobLoneform: "Löneform",
    jobAntal: "Antal lediga befattningar",
    jobSysselsattningsgrad: "Sysselsättningsgrad",
    jobOrt: "Ort",
    jobLan: "Län",
    jobLand: "Land",
    jobReferensnummer: "Referensnummer",
    jobKontakt: "Kontakt",
    jobPublicerat: "Publicerat",
    jobSistaAnsokningsdag: "Sista ansökningsdag",
    jobFack: "Fackliga representanter",
    
    journalNumber: "Utgivningsnummer",
    journalTitle: "Tidskrift",
    keywords: "Forskningsområden",
    keywords_uka: "UKÄ",
    keywords_user: "Nyckelord",
    language: "Språk",
    more: "Mer",
    moreFilteringOptions: "Fler filtreringsmöjlighter",
    namelabel: "Namn",
    next: "Nästa",
    next: "Nästa",
    No: "Inga",
    nohits: "Din sökning - ###term### - matchade inte något dokument.",
    numberOfPages: "Antal sidor",
    numberOfPages: "Sidantal",
    of: "av",
    on: "på",
    organisations: "Enheter och grupper",
    organisationLeaveOfAbsence: "Leave of Absence",
    overview: "Översikt",
    pages: "Sidor",
    pagesAbbreviation: "s.",
    peerReview: "Peer review utförd",
    people: "Personal",
    personal_homepage: "Personlig hemsida",
    phone: "Telefon",
    placeOfPublication: "Utgivningsort",
    prev: "Förra",
    printIsbns: "Tryckta ISBN",
    publicationDateYear: "År",
    publications: "Publikationer",
    publicationStatus: "Status",
    publicationYear: "Publikationsår",
    publisher: "Förlag",
    read_more_about: "Läs mer om",
    room: "Rum",
    show_all: "Visa alla",
    show_more: "Visa fler",
    show_selection: "Visa urval",
    staff_categories: "Personalkategorier",
    state: "Status",
    supervisor: "Handledare",
    supervisors: "Handledare",
    title: "Titel",
    type: "Typ",
    webpages: "Webbsidor",
    within: "inom",
    volume: "Volym",
};

