var lth_solr_messages = {
    show_all: "Visa alla",
    show_more: "Visa fler",
    next: "Nästa",
    prev: "Förra",
    show_selection: "Visa urval",
    staff_categories: "Personalkategorier",
    personal_homepage: "Personlig hemsida",
    room: "Rum",
    phone: "Telefon",
    of: "av",
    namelabel: "Namn",
    authors: "Författare",
    organisations: "Enheter och grupper",
    language: "Språk",
    pages: "Sidor",
    numberOfPages: "Sidantal",
    publicationStatus: "Status",
    peerReview: "Peer review utförd",
    read_more_about: "Läs mer om",
    more: "Mer",
    close: "Stäng",
    next: "Nästa",
    people: "Personal",
    documents: "Dokument",
    webpages: "Webbsidor",
    publications: "Publikationer",
    nohits: "Din sökning - ###term### - matchade inte något dokument.",
    abstract: "Abstract",
    volume: "Volym",
    journalNumber: "Utgivningsnummer",
    journalTitle: "Tidskrift",
    numberOfPages: "Antal sidor",
    keywords: "Forskningsområden",
    courses: "Kurser"
};

