var lth_solr_messages = {
    abstract: "Abstract",
    additionalLink: "Additional links",
    authorLastName: "Lastname",
    authors: "Authors",
    close: "Close",
    courses: "Courses",
    documents: "Documents",
    doi: "DOI",
    edition: "Edition",
    electronicIsbns: "Electronic ISBN",
    event: "Evenemang",
    externalOrganisations: "External organisations",
    export: "EXPORT SEARCH RESULT",
    filterSearchResult: "FILTER SEARCH RESULT",
    fulltext: "Full text",
    hits: "hits",
    hostPublicationTitle: "Title of host publication",
    in: "in",
    journalNumber: "Issue number",
    journalTitle: "Journal",
    keywords: "Research areas and keywords",
    keywords_uka: "UKÄ",
    keywords_user: "Keywords",
    language: "Original languages",
    more: "More",
    moreFilteringOptions: "More filtering options",
    namelabel: "Name",
    next: "Next",
    next: "Next",
    No: "No",
    nohits: "Your search - ###term### - did not match any document",
    numberOfPages: "Number of pages",
    numberOfPages: "Number of pages",
    of: "of",
    on: "on",
    organisationLeaveOfAbsence: "Leave of Absence",
    organisations: "Organisations",
    overview: "Overview",
    pages: "Pages",
    pagesAbbreviation: "p.",
    peerReview: "Per-reviewed",
    people: "People",
    personal_homepage: "Personal homepage",
    phone: "Phone",
    placeOfPublication: "Place of Publication",
    prev: "Previous",
    printIsbns: "Print ISBN",
    publicationDateYear: "Year",
    publications: "Publications",
    publicationStatus: "State",
    publicationYear: "Publication Year",
    publisher: "Publisher",
    read_more_about: "Read more about",
    room: "Room",
    show_all: "Show all",
    show_more: "Show more",
    show_selection: "Show selection",
    staff_categories: "Staff categories",
    state: "Status",
    supervisor: "Supervisor",
    supervisors: "Supervisors/Advisors",
    title: "Title",
    type: "Type",
    volume: "Volume",
    webpages: "Web pages",
    within: "within",
};


