var lth_solr_messages = {
    show_all: "Show all",
    show_more: "Show more",
    next: "Next",
    prev: "Previous",
    show_selection: "Show selection",
    staff_categories: "Staff categories",
    personal_homepage: "Personal homepage",
    room: "Room",
    phone: "Phone",
    of: "of",
    namelabel: "Name",
    authors: "Authors",
    organisations: "Organisations",
    language: "Original languages",
    pages: "Pages",
    numberOfPages: "Number of pages",
    publicationStatus: "State",
    peerReview: "Per-reviewed",
    read_more_about: "Read more about",
    more: "More",
    close: "Close",
    next: "Next",
    people: "People",
    documents: "Documents",
    webpages: "Web pages",
    publications: "Publications",
    nohits: "Your search - ###term### - did not match any document",
    abstract: "Abstract",
    volume: "Volume",
    journalNumber: "Issue number",
    journalTitle: "Journal",
    numberOfPages: "Number of pages",
    keywords: "Research areas and keywords",
    courses: "Courses"
};


